#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a URxvt:scratchy sticky=on state=floating rectangle=widthxheight+Xoffset+Yoffset

bspc config border_width         4
bspc config border_radius         12
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# --------------------------------
# ------- Non-BSPWM related ------
# --------------------------------

#Pywal  colors to script
. ${HOME}/.cache/wal/colors.sh

# Reload .Xresources
xrdb -load ~/.Xresources
# Launch polybar
~/.config/polybar/launch.sh
# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr
dunst &
# Nm-applet
nm-applet &
#My Background
wal -i /home/iamtrashu/Imágenes/ghostinshell.jpg & 

#NoBordersExceptOnBSPWM
bspc config normal_border_color "$color1"
bspc config active_border_color "$color5"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

